site_name: vega-save
repo_url: https://github.com/SyntaxRules/vega-save/
theme: readthedocs
pages:
    - 'Overview': 'index.md'
    - 'User Guide':
        - 'Quick Start': 'quick-start.md'
        - 'Installation Instructions': 'installation-instructions.md'
    - 'License': 'license.md'